name = "LMFDB"
uuid = "d66269b8-7907-4a75-8041-d35544a92097"
version = "0.1.0"
authors = ["Tommy Hofmann <thofma@gmail.com>"]

[deps]
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
LMFDBLite = "3b60bc14-21d8-482a-b05a-6415f8768d32"

[sources]
LMFDBLite = {rev = "main", url = "https://github.com/thofma/LMFDBLite.jl"}

[compat]
Hecke = "0.39.12"
